### ISSUE TITLE
General System Flow

### ISSUE THREAD

**Issue by arifinBLvynhart** [arifinBLvynhart/swrwg#1]
Gambaran flow sistem secara general.

**Comment by sandesign01** [comment]
ok, siap laksanakan bos!

**Comment by arifinBLvynhart** [comment]
Ini aku closed ya, mulai sekarang hal-hal yang masih berkaitan dengan konsep dibicarakan di trello. Kalau sudah ready to develop baru masuk kesini, thank u.

https://trello.com/b/hY3qOOVj/kitabook-com
